version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: nest_mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: dps-tracker
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
